# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Delete.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Delete_Window(object):
    def setupUi(self, Delete_Window):
        Delete_Window.setObjectName("Delete_Window")
        Delete_Window.resize(400, 258)
        Delete_Window.setMinimumSize(QtCore.QSize(400, 258))
        Delete_Window.setMaximumSize(QtCore.QSize(400, 258))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icon/2252295991582004497-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Delete_Window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Delete_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox_target = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_target.setGeometry(QtCore.QRect(200, 30, 171, 36))
        self.comboBox_target.setObjectName("comboBox_target")
        self.pushButton_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cancel.setGeometry(QtCore.QRect(280, 200, 99, 38))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icon/12355707351582004488-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_cancel.setIcon(icon1)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.pushButton_ok = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ok.setGeometry(QtCore.QRect(170, 200, 99, 38))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icon/7774226221582004489-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ok.setIcon(icon2)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.lineEdit_Username = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Username.setGeometry(QtCore.QRect(160, 80, 211, 36))
        self.lineEdit_Username.setObjectName("lineEdit_Username")
        self.lineEdit_Password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Password.setGeometry(QtCore.QRect(160, 120, 211, 36))
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.label_Username = QtWidgets.QLabel(self.centralwidget)
        self.label_Username.setGeometry(QtCore.QRect(40, 90, 101, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_Username.setFont(font)
        self.label_Username.setObjectName("label_Username")
        self.label_Password = QtWidgets.QLabel(self.centralwidget)
        self.label_Password.setGeometry(QtCore.QRect(40, 130, 81, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_Password.setFont(font)
        self.label_Password.setObjectName("label_Password")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        Delete_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Delete_Window)
        QtCore.QMetaObject.connectSlotsByName(Delete_Window)

    def retranslateUi(self, Delete_Window):
        _translate = QtCore.QCoreApplication.translate
        Delete_Window.setWindowTitle(_translate("Delete_Window", "Delete"))
        self.comboBox_target.setToolTip(_translate("Delete_Window", "Select your target"))
        self.pushButton_cancel.setText(_translate("Delete_Window", "Cancel"))
        self.pushButton_ok.setText(_translate("Delete_Window", "OK"))
        self.lineEdit_Username.setToolTip(_translate("Delete_Window", "Enter Username or Hostname"))
        self.lineEdit_Password.setToolTip(_translate("Delete_Window", "Enter Password"))
        self.label_Username.setText(_translate("Delete_Window", "User or Host:"))
        self.label_Password.setText(_translate("Delete_Window", "Password:"))
        self.label.setText(_translate("Delete_Window", "Delete one"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Delete_Window = QtWidgets.QMainWindow()
    ui = Ui_Delete_Window()
    ui.setupUi(Delete_Window)
    Delete_Window.show()
    sys.exit(app.exec_())
