# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/create_script_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Create_script_Window(object):
    def SetupUi_create_script(self, Create_script_Window):
        Create_script_Window.setObjectName("Create_script_Window")
        Create_script_Window.resize(552, 182)
        Create_script_Window.setMinimumSize(QtCore.QSize(552, 182))
        Create_script_Window.setMaximumSize(QtCore.QSize(552, 182))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI/../icon/2252295991582004497-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Create_script_Window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Create_script_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 91, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 20, 67, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 67, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_script_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_script_name.setGeometry(QtCore.QRect(110, 20, 171, 31))
        font = QtGui.QFont()
        font.setItalic(True)
        self.lineEdit_script_name.setFont(font)
        self.lineEdit_script_name.setObjectName("lineEdit_script_name")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(370, 20, 171, 31))
        font = QtGui.QFont()
        font.setItalic(True)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 80, 531, 36))
        font = QtGui.QFont()
        font.setItalic(True)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cancel.setGeometry(QtCore.QRect(440, 130, 99, 38))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("UI/../icon/12355707351582004488-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_cancel.setIcon(icon1)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.pushButton_ok = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ok.setGeometry(QtCore.QRect(330, 130, 99, 38))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("UI/../icon/7774226221582004489-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ok.setIcon(icon2)
        self.pushButton_ok.setObjectName("pushButton_ok")
        Create_script_Window.setCentralWidget(self.centralwidget)

        self.RetranslateUi_create_script(Create_script_Window)
        QtCore.QMetaObject.connectSlotsByName(Create_script_Window)

    def RetranslateUi_create_script(self, Create_script_Window):
        _translate = QtCore.QCoreApplication.translate
        Create_script_Window.setWindowTitle(_translate("Create_script_Window", "Create script"))
        Create_script_Window.setToolTip(_translate("Create_script_Window", "Create script window"))
        self.label.setText(_translate("Create_script_Window", "Script name:"))
        self.label_2.setText(_translate("Create_script_Window", "Usability:"))
        self.label_3.setText(_translate("Create_script_Window", "path:"))
        self.lineEdit_script_name.setToolTip(_translate("Create_script_Window", "Enter script_name.py"))
        self.lineEdit_script_name.setPlaceholderText(_translate("Create_script_Window", "script name"))
        self.lineEdit_2.setToolTip(_translate("Create_script_Window", "Enter script usability"))
        self.lineEdit_2.setPlaceholderText(_translate("Create_script_Window", "usability"))
        self.lineEdit_3.setToolTip(_translate("Create_script_Window", "Enter path script"))
        self.lineEdit_3.setPlaceholderText(_translate("Create_script_Window", "path:"))
        self.pushButton_cancel.setText(_translate("Create_script_Window", "Cancel"))
        self.pushButton_ok.setText(_translate("Create_script_Window", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Create_script_Window = QtWidgets.QMainWindow()
    ui = Ui_Create_script_Window()
    ui.SetupUi_create_script(Create_script_Window)
    Create_script_Window.show()
    sys.exit(app.exec_())
